port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B79032752-if00 # linux stable by-id, Feetech CH340 adapter
#port: /dev/ttyUSB0 # linux (legacy)
version: 0.2.1
baudrate: 1000000
max_current: 950
type: left
motor_type: feetech
control_mode: current_based_position
disabled_motor_ids:
- 1
- 2
motor_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
joint_ids:
- thumb_mcp
- thumb_abd
- thumb_pip
- thumb_dip
- index_abd
- index_mcp
- index_pip
- middle_abd
- middle_mcp
- middle_pip
- ring_abd
- ring_mcp
- ring_pip
- pinky_abd
- pinky_mcp
- pinky_pip
- wrist
joint_to_motor_map:
  thumb_mcp: 9
  thumb_abd: 6
  thumb_pip: 7
  thumb_dip: 8
  index_abd: 12
  index_mcp: 11
  index_pip: 10
  middle_abd: 13
  middle_mcp: -2
  middle_pip: 17
  ring_abd: 14
  ring_mcp: -15
  ring_pip: 16
  pinky_abd: -5
  pinky_mcp: 4
  pinky_pip: 3
  wrist: -1

joint_roms:
  thumb_mcp:
  - -45
  - 33
  thumb_abd:
  - -18
  - 55
  thumb_pip:
  - -25
  - 100
  thumb_dip:
  - -15
  - 107
  index_abd:
  - -30
  - 25
  index_mcp:
  - -25
  - 100
  index_pip:
  - -15
  - 107
  middle_abd:
  - -27
  - 27
  middle_mcp:
  - -25
  - 100
  middle_pip:
  - -15
  - 107
  ring_abd:
  - -27
  - 27
  ring_mcp:
  - -25
  - 100
  ring_pip:
  - -15
  - 107
  pinky_abd:
  - -30
  - 30
  pinky_mcp:
  - -25
  - 100
  pinky_pip:
  - -15
  - 107
  wrist:
  - -65
  - 35
neutral_position:
  thumb_mcp: 0
  thumb_abd: 50
  thumb_pip: 33
  thumb_dip: 18
  index_abd: -14
  index_mcp: 2
  index_pip: 6
  middle_abd: -4
  middle_mcp: 2
  middle_pip: 4
  ring_abd: 10
  ring_mcp: -2
  ring_pip: 8
  pinky_abd: 22
  pinky_mcp: -4
  pinky_pip: -2
  wrist: -20
wrist_calib_current: 950
calibration_current: 450
calibration_step_size: 0.08
calibration_step_period: 0.01
calibration_num_stable: 25
calibration_threshold: 0.01
calibration_sequence:
- step: 1
  joints:
    thumb_mcp: flex
- step: 2
  joints:
    thumb_mcp: extend
- step: 3
  joints:
    thumb_abd: flex
- step: 4
  joints:
    thumb_abd: extend
- step: 5
  joints:
    thumb_pip: flex
- step: 6
  joints:
    thumb_pip: extend
- step: 7
  joints:
    thumb_dip: flex
- step: 8
  joints:
    thumb_dip: extend
- step: 9
  joints:
    index_abd: flex
    middle_abd: flex
    ring_abd: flex
    pinky_abd: flex
- step: 10
  joints:
    index_abd: extend
    middle_abd: extend
    ring_abd: extend
    pinky_abd: extend
- step: 11
  joints:
    index_mcp: flex
    middle_mcp: flex
    ring_mcp: flex
    pinky_mcp: flex
- step: 12
  joints:
    index_mcp: extend
    middle_mcp: extend
    ring_mcp: extend
    pinky_mcp: extend
- step: 13
  joints:
    index_pip: flex
    middle_pip: flex
    ring_pip: flex
    pinky_pip: flex
- step: 14
  joints:
    index_pip: extend
    middle_pip: extend
    ring_pip: extend
    pinky_pip: extend
- step: 15
  joints:
    wrist: flex
- step: 16
  joints:
    wrist: extend
